//! Generates compile-time lookup tables from JSON data files:
//!
//! - `locales/*.json` — UI copy, `{ "key": { "en": "...", "la": "...", ... } }`.
//!   Adding a language to an existing key is a JSON edit only. Output: `t_raw`
//!   in `OUT_DIR/i18n_generated.rs`, included by `src/i18n.rs`.
//! - `data/models.json` — model catalog flavor text, `{ "model-id": { "name":
//!   "...", "en": "...", "la": "..." } }`. Output: `model_catalog_raw` in
//!   `OUT_DIR/model_catalog_generated.rs`, included by `src/routes/models_page.rs`.

use std::collections::BTreeMap;
use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

fn json_files_in(dir: &Path) -> Vec<PathBuf> {
    println!("cargo:rerun-if-changed={}", dir.display());
    let mut entries: Vec<PathBuf> = fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("failed to read {}: {}", dir.display(), e))
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|ext| ext == "json"))
        .collect();
    entries.sort();
    entries
}

fn read_json<T: serde::de::DeserializeOwned>(path: &Path) -> T {
    println!("cargo:rerun-if-changed={}", path.display());
    let content =
        fs::read_to_string(path).unwrap_or_else(|e| panic!("failed to read {}: {}", path.display(), e));
    serde_json::from_str(&content).unwrap_or_else(|e| panic!("invalid JSON in {}: {}", path.display(), e))
}

fn write_generated(out_dir: &Path, filename: &str, contents: &str) {
    fs::write(out_dir.join(filename), contents)
        .unwrap_or_else(|e| panic!("failed to write {filename}: {e}"));
}

/// Codegens `t_raw(locale_code, key) -> Option<&'static str>` from `locales/*.json`.
fn generate_i18n_table(out_dir: &Path) {
    let mut table: BTreeMap<String, BTreeMap<String, String>> = BTreeMap::new();

    for path in json_files_in(Path::new("locales")) {
        let parsed: BTreeMap<String, BTreeMap<String, String>> = read_json(&path);
        for (key, translations) in parsed {
            if let Some(existing) = table.insert(key.clone(), translations) {
                panic!(
                    "duplicate i18n key '{key}' found across locale files (previous translations: {existing:?})"
                );
            }
        }
    }

    let mut out = String::new();
    out.push_str("// @generated by build.rs from locales/*.json — do not edit by hand.\n");
    out.push_str("pub(crate) fn t_raw(locale_code: &str, key: &str) -> Option<&'static str> {\n");
    out.push_str("    match key {\n");
    for (key, translations) in &table {
        writeln!(out, "        {key:?} => match locale_code {{").unwrap();
        for (code, text) in translations {
            writeln!(out, "            {code:?} => Some({text:?}),").unwrap();
        }
        out.push_str("            _ => None,\n");
        out.push_str("        },\n");
    }
    out.push_str("        _ => None,\n");
    out.push_str("    }\n");
    out.push_str("}\n");

    write_generated(out_dir, "i18n_generated.rs", &out);
}

/// Codegens `model_catalog_raw(id) -> Option<(name, en_desc, la_desc)>` from `data/models.json`.
fn generate_model_catalog(out_dir: &Path) {
    #[derive(serde::Deserialize)]
    struct ModelEntry {
        name: String,
        en: String,
        la: String,
    }

    let mut catalog: BTreeMap<String, ModelEntry> = BTreeMap::new();
    for path in json_files_in(Path::new("data")) {
        let parsed: BTreeMap<String, ModelEntry> = read_json(&path);
        for (id, entry) in parsed {
            if catalog.insert(id.clone(), entry).is_some() {
                panic!("duplicate model id '{id}' found across data/*.json files");
            }
        }
    }

    let mut out = String::new();
    out.push_str("// @generated by build.rs from data/*.json — do not edit by hand.\n");
    out.push_str(
        "pub(crate) fn model_catalog_raw(model_id: &str) -> Option<(&'static str, &'static str, &'static str)> {\n",
    );
    out.push_str("    match model_id {\n");
    for (id, entry) in &catalog {
        writeln!(out, "        {id:?} => Some(({:?}, {:?}, {:?})),", entry.name, entry.en, entry.la).unwrap();
    }
    out.push_str("        _ => None,\n");
    out.push_str("    }\n");
    out.push_str("}\n");

    write_generated(out_dir, "model_catalog_generated.rs", &out);
}

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR set by cargo"));
    generate_i18n_table(&out_dir);
    generate_model_catalog(&out_dir);
}
